name: PR

on:
  pull_request:
    paths-ignore:
      - README.md

  workflow_dispatch:

jobs:
  checks-ubuntu:
    uses: ./.github/workflows/reusable-pr.yaml
    with:
      runner: ubuntu-latest
  checks-macos:
    uses: ./.github/workflows/reusable-pr.yaml
    with:
      runner: macos-latest
